### PR TITLE
Add initial docs for sparkR with Cassandra Connector

### PR DESCRIPTION
**Pull request by harrison-tarr**
# Description
Documentation update for SparkR compatibility

## How did the Spark Cassandra Connector Work or Not Work Before this Patch

It was hard to get started without an intimate knowledge of the SparkR API. These instructions should make it easier to pick it up and start experimenting.

## General Design of the patch

It is a new documentation file with a unique integer number at the beginning of the file name, following the pattern of the others.

# How Has This Been Tested?

Manually verified every step that was added in a sparkR shell running against a local Cassandra.

# Checklist:

- [ ] I have a ticket in the [OSS JIRA](https://datastax-oss.atlassian.net/projects/SPARKC) (possibly n/a, i don't want to clutter the jira with doc tickets - happy to add one if that is the right approach)
- [X] I have performed a self-review of my own code
- [ ] Locally all tests pass (make sure tests fail without your patch) (i dont' think this would need to be tested?)

### CODE REVIEW

**Comment by harrison-tarr** [comment]
this doc update is accurate for all the first steps. I wasn't sure about some of the subsequent DSL examples that work in Scala. Does anyone know if there is a corresponding SparkR DSL that can be used to make those same calls or is it all `sql()`?

**Comment by harrison-tarr** [comment]
For reference, this was discussed in the google group yesterday/today (Jan 6, 7 2021) https://groups.google.com/u/1/a/lists.datastax.com/g/spark-connector-user/c/KWmLrs1nvBM/m/5zj2qhC-CAAJ

**Comment by alexott** [comment]
Here is more: https://stackoverflow.com/questions/41601715/integration-of-spark2-0-and-cassandra-using-r/57107100#57107100

**Comment by harrison-tarr** [comment]
Hi again Alex,

Thanks for the additional information, it's really helpful. I had seen the
'read.df' syntax and couldn't figure out how to make it work against the
Cassandra Connector so I had been using 'sql' calls, but now I have the
option of both!

I have a new question about an error I'm seeing when joining two
SparkDataFrames after running 'regexp_replace'. I have two dataframes that
I want to join on the ids, but one of the ids has the string "#hidden"
appended. I try to run the 'regexp_replace(dataframeA$column, "#hidden",
"") and then a join(dataframeA, dataframeB,
dataframeA$column==dataframeB$id)

When I try to run any subsequent commands, like head() on the result, it
fails with the following error:
Error in handleErrors(returnStatus, conn) :
  scala.MatchError: regexp_replace(id#175, #hidden,  ) AS id_fixed#187 (of
class org.apache.spark.sql.catalyst.expressions.Alias)
at
org.apache.spark.sql.cassandra.execution.CassandraDirectJoinStrategy$.$anonfun$aliasMap$1(CassandraDirectJoinStrategy.scala:315)
at
scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
at scala.collection.TraversableLike.map(TraversableLike.scala:238)
at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
at scala.collection.AbstractTraversable.map(Traversable.scala:108)
at
org.apache.spark.sql.cassandra.execution.CassandraDirectJoinStrategy$.aliasMap(CassandraDirectJoinStrategy.scala:315)
at
org.apache.spark.sql.cassandra.execution.CassandraDirectJoinStrategy$.allPartitionKeysAreJoin

Do I need to do something special to execute a 'regexp_replace'? When I
execute the join without the 'regexp_replace', I can do a head() on the
result, but obviously, the dataframe is empty.

**Comment by alexott** [comment]
please post the bigger, snippet of the code. Also, this is more a question for StackOverflow, or mailing list, not in the context of the pull request...
I suspect that you need to alias the result of `regex_replace` to give it a name matching to the column in database.

**Comment by harrison-tarr** [comment]
oops, i thought i was replying to the mailing list thread! my mistake. I will continue the discussion there

**Pull request closed without merging**
