### PR TITLE
Added a few more tasks to travis ci

### PR DESCRIPTION
**Pull request by helena**
https://datastax-oss.atlassian.net/browse/SPARKC-17

### CODE REVIEW

**Comment by helena** [comment]
@jacek-lewandowski @pkolaczk this needs review

**Comment by pkolaczk** [comment]
+1, I'd like to make travis perform integration tests as well. Why isn't it possible?

**Comment by helena** [comment]
@pkolaczk i tried this, and could not quickly get the embedded cassandra usage working on travis, it needs settings available.

**Comment by helena** [comment]
@pkolaczk when things slow down next I'll take a look again at running ITs in Travis

**Pull request merged**
