### PR TITLE
SPARKC-88 DStream repartition and join functions

### PR DESCRIPTION
**Pull request by RussellSpitzer**

### CODE REVIEW

**Comment by pkolaczk** [comment]
+1, just fix the alignment

**Comment by RussellSpitzer** [comment]
Cleaned up the entire file's alignment so it would match

**Comment by pkolaczk** [comment]
```
[info] Compiling 17 Scala sources to /home/travis/build/datastax/spark-cassandra-connector/spark-cassandra-connector/target/scala-2.10/it-classes...

[error] /home/travis/build/datastax/spark-cassandra-connector/spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/streaming/ActorStreamSpec.scala:133: not found: value sc

[error] sc.cassandraTable("demo", "dstream_join_output").collect.size should be(data.size)

[error] ^

[error] one error found

[error] (spark-cassandra-connector/it:compileIncremental) Compilation failed
```

**Comment by RussellSpitzer** [comment]
Updated test files, letting travis run

**Pull request merged**
