### PR TITLE
Don't double resolve the file in DynamicCassandraPorts.

### PR DESCRIPTION
**Pull request by crakjie**
because the directory is resolve just once it's make an exception because directories are twice in the path but the second part is no created.

more detail [here](https://groups.google.com/a/lists.datastax.com/forum/#!topic/spark-connector-user/rokkNyJE3UQ)

### CODE REVIEW

**Comment by jotsif** [comment]
I also have this issue and added a JIRA for it: 

https://datastax-oss.atlassian.net/browse/SPARKC-316

**Comment by crakjie** [comment]
I have to register into this lira?

**Comment by crakjie** [comment]
I never receive the confirmation mail from datastax Jira. Please can you add this PR to your lira ticket?

**Comment by jotsif** [comment]
Yes, issues are handled by Datastax in their issue tracker.

Ok, I can add PR.

**Comment by crakjie** [comment]
Thanks @jotsif ! :+1:

**Pull request closed without merging**
