### PR TITLE
Sparkc-73 support cross cluster table join for Spark SQL Cassandra integration

### PR DESCRIPTION
**Pull request by alexliu68**
For integration tests, set 127.0.0.2 as a loopback alias address.

### CODE REVIEW

**Comment by jacek-lewandowski** [comment]
You should also take a look into `RDDFunctions` - I think these methods should also get `cluster` parameter.

**Comment by jacek-lewandowski** [comment]
Also either add support for this in Java API or create a separate ticket to make sure we won't forget about it before release.

**Comment by jacek-lewandowski** [comment]
For SharedEmbeddedCassandra - I'd really like it to be a kind of flexible array rather than hardcoded two objects. And we should have a single configuration yaml with more configurable fields. Your change will greatly improve our ability to do integration tests. However, if you make it more generic, we will benefit even more.

**Comment by jacek-lewandowski** [comment]
First round of review done

**Comment by alexliu68** [comment]
Can we open another ticket to improve the testing infrastructure(It will be big enough for a separate ticket :))? Let the function implementation be done in this PR?

**Comment by jacek-lewandowski** [comment]
So, at least please eliminate use of the second yaml file (add more placeholder to the one we use now) and please create the other tickets to cover those missing fixes.

**Comment by jacek-lewandowski** [comment]
Also, please make sure to not run the tests which require another localhost address to be configured. Just show some warning in that case and ignore the test. 

After rebasing, there will be a script {{dev/run-tests.sh}}. You can add the configuration of additional loopback address in that file.

**Pull request closed without merging**
