### PR TITLE
Add support for null UDT values.

### PR DESCRIPTION
**Pull request by dragisak**

### CODE REVIEW

**Comment by dragisak** [comment]
I've seen this too. Build is failing with: `sbt.ResolveException: unresolved dependency: org.apache.spark#spark-unsafe_2.10;1.5.0: not found`

**Comment by bcantoni** [comment]
retest this please

**Comment by dragisak** [comment]
Same problem it seems:
```
[error] (spark-cassandra-connector-embedded/*:update) sbt.ResolveException: unresolved dependency: org.apache.spark#spark-unsafe_2.10;1.5.0: not found
```

**Comment by dragisak** [comment]
retest this please

**Comment by dragisak** [comment]
retest this please

**Comment by RussellSpitzer** [comment]
retest this please

**Comment by vfelberg** [comment]
In 1.5.0-M1, you have to patch one more file:

```
diff --git a/spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/MappedToGettableDataConverter.scala b/spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/MappedToGettableDataConverter.scala
index 3882d4e..94e31bb 100644
--- a/spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/MappedToGettableDataConverter.scala
+++ b/spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/MappedToGettableDataConverter.scala
@@ -8,14 +8,14 @@ import com.datastax.spark.connector.util.{Symbols, ReflectionUtil}
 import com.datastax.spark.connector.{GettableByIndexData, TupleValue, UDTValue, ColumnRef}
 import com.datastax.spark.connector.cql.StructDef
 import com.datastax.spark.connector.mapper.{DefaultColumnMapper, TupleColumnMapper, JavaBeanColumnMapper, ColumnMapper}
-import com.datastax.spark.connector.types.{TupleType, MapType, SetType, ListType, ColumnType, TypeConverter}
+import com.datastax.spark.connector.types._
 
 private[connector] object MappedToGettableDataConverter {
 
   def apply[T : TypeTag : ColumnMapper]
       (struct: StructDef, columnSelection: IndexedSeq[ColumnRef]): TypeConverter[struct.ValueRepr] =
 
-    new TypeConverter[struct.ValueRepr] {
+    new NullableTypeConverter[struct.ValueRepr] {
 
       /** To determine which default column mapper to use for UDT fields.
         * If this class is a Java bean, then the UDT fields will be mapped with
```

**Comment by dragisak** [comment]
I rebased it on top of current master.

**Comment by dragisak** [comment]
retest this please

**Comment by RussellSpitzer** [comment]
retest this please

**Comment by RussellSpitzer** [comment]
Thanks for the PR! Sorry that it took so long to get to

**Pull request merged**
