### PR TITLE
Update Spark version to 2.4.0 and make sure it is supported

### PR DESCRIPTION
**Pull request by nikolovivan**
This is a fix for https://datastax-oss.atlassian.net/browse/SPARKC-553.

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
Thanks for the fix! I'll try to quick off the tests

**Comment by RussellSpitzer** [comment]
test this please

**Comment by RussellSpitzer** [comment]
Jenkins can't hear me, i'll run them manually

**Comment by RussellSpitzer** [comment]
test this please

**Comment by RussellSpitzer** [comment]
Excellent tests are running

**Comment by RussellSpitzer** [comment]
@nikolovivan looks like there is one more issue in the com.datastax.spark.connector.repl.CassandraRDDReplSpec
Another class not found. Fix up that test and I think we are good to go

**Comment by nikolovivan** [comment]
Hey, I forgot that I had troubles last time running the integration tests and I had to run them from a clean Docker container. Just did it and I think I had to bump the Scala version to the same number they've used in Spark to fix the error.

I don't have the time to run the tests fully at the moment as I have to run, but feel free to trigger them again. If there are issues, I'll spend time properly addressing them over the weekend.

**Comment by RussellSpitzer** [comment]
this this please

**Comment by RussellSpitzer** [comment]
> Hey, I forgot that I had troubles last time running the integration tests and I had to run them from a clean Docker container. Just did it and I think I had to bump the Scala version to the same number they've used in Spark to fix the error.
> 
> I don't have the time to run the tests fully at the moment as I have to run, but feel free to trigger them again. If there are issues, I'll spend time properly addressing them over the weekend.

No problem i'll trigger everything again

**Comment by RussellSpitzer** [comment]
test this please

**Comment by RussellSpitzer** [comment]
for some reason I have to say it twice ... or maybe since I was looking at the configuration it felt bad and decided to work the second time

**Comment by nikolovivan** [comment]
Looks like it's passing for `2.11`, which is the only supported version since 2.3, so I guess it's good now.

Let me know if you would prefer me to see which could be the lowest possible version between `2.11.8` and `2.11.12` that would make the build pass?

**Comment by nikolovivan** [comment]
I just checked and we could go as low as `2.11.9` if we wanted to. Might be best to keep it consistent with what version Spark 2.4.0 uses, though (`2.11.12`). Let me know what you prefer.

**Comment by igreenfield** [comment]
Does this also add support for scala 2.12?

**Comment by nikolovivan** [comment]
No, it doesn't. Adding support for 2.12 might be trivial, but might also involve changing lots of other library versions and code.

**Comment by RussellSpitzer** [comment]
2.10 Shouldn't pass on master (I just forgot to turn off triggering it) so This is good to go

**Comment by nikolovivan** [comment]
Do you have an idea when you'll be merging this one and releasing a new version?

**Comment by purijatin** [comment]
> No, it doesn't. Adding support for 2.12 might be trivial, but might also involve changing lots of other library versions and code.

Yes. 

Based on [this](http://apache-spark-developers-list.1001551.n3.nabble.com/Make-Scala-2-12-as-default-Scala-version-in-Spark-3-0-tp25641p25676.html), looks like scala 2.12 is going to be the default scala version going forward.

**Comment by simpadjo** [comment]
I've easily built the project against scala 2.12 but I had to disable the scoverage plugin.
Seems that enabling it requires upgrading sbt.

**Comment by nikolovivan** [comment]
@RussellSpitzer do you have any idea when you're planning on merging this and releasing a new version. Let me know if I can help in any way.

**Comment by purijatin** [comment]
any update here?

**Comment by RussellSpitzer** [comment]
Just finished getting caught up at work, I'll do a release tonight.

**Pull request merged**
