### PR TITLE
SPARKC-118: Add an ability to configure encryption of connection to Cassandra

### PR DESCRIPTION
**Pull request by jacek-lewandowski**

### CODE REVIEW

**Comment by sdelmas** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by artem-aliev** [comment]
Should the SparkContext(SparcConf()) IT test added to check that options is passed from user level?

**Comment by jacek-lewandowski** [comment]
@artem-aliev ok - will add tests

**Comment by artem-aliev** [comment]
all other +1

**Pull request merged**
