### PR TITLE
[SPARKC-144] Add sbt-spark-package support for easy release management on Spark Packages

### PR DESCRIPTION
**Pull request by brkyvz**
@RussellSpitzer I made this a different PR, because GitHub couldn't handle the number of commits and the diff on top of your PR :)

Could you please help with testing? The commands that are of relevance are `spark-cassandra-connector/spDist` and `spark-cassandra-connector/spPublish`. If you would also like to publish the java connector as well, I suggest creating a separate Spark Package on the website, and then using `spark-cassandra-connector-java/spPublish`.

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
I'll check this out, but i'll need to wait for Piotr to come back for some credentials

**Comment by brkyvz** [comment]
If you have admin access on the repo, you can try it yourself as well

**Comment by pkolaczk** [comment]
I can't build it, I'm getting:
```
[info] Resolving org.spark-packages#sbt-spark-package;0.2.2 ...
[warn] 	module not found: org.spark-packages#sbt-spark-package;0.2.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.spark-packages/sbt-spark-package/scala_2.10/sbt_0.13/0.2.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.spark-packages/sbt-spark-package/scala_2.10/sbt_0.13/0.2.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/pkolaczk/.ivy2/local/org.spark-packages/sbt-spark-package/scala_2.10/sbt_0.13/0.2.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/spark-packages/sbt-spark-package_2.10_0.13/0.2.2/sbt-spark-package-0.2.2.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/org/spark-packages/sbt-spark-package_2.10_0.13/0.2.2/sbt-spark-package-0.2.2.pom
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.spark-packages/sbt-spark-package/scala_2.10/sbt_0.13/0.2.2/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.spark-packages#sbt-spark-package;0.2.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.spark-packages:sbt-spark-package:0.2.2 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.spark-packages:sbt-spark-package:0.2.2 (scalaVersion=2.10, sbtVersion=0.13) (/home/pkolaczk/Projekty/DataStax/spark-cassandra-connector/project/plugins.sbt#L20-21)
[warn] 		  +- default:spark-cassandra-connector-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
```

**Comment by pkolaczk** [comment]
Do we need to add anything to the project dependency repositories?

**Comment by brkyvz** [comment]
@pkolaczk The ivy format maven format resolution is very annoying. Even though the package was linked to the sbt-plugins-repo, it couldn't resolve it because of the maven format. I added back the resolver, should work now.

**Comment by brkyvz** [comment]
@pkolaczk Did you get a chance to retry this?

**Comment by pkolaczk** [comment]
It is much better now, spDist works. The only minor problem is that it tries to package also some subprojects that are not configured. Is there an easy way to exclude these?

```
[trace] Stack trace suppressed: run last twitter-streaming/*:packageOptions for the full output.
[trace] Stack trace suppressed: run last twitter-streaming/*:spPackage for the full output.
[trace] Stack trace suppressed: run last spark-cassandra-connector-embedded/*:packageOptions for the full output.
[trace] Stack trace suppressed: run last spark-cassandra-connector-embedded/*:spPackage for the full output.
[error] (twitter-streaming/*:packageOptions) Please add any Spark dependencies by supplying the sparkVersion and sparkComponents. Please remove: org.apache.spark:spark-streaming:1.4.0
[error] (twitter-streaming/*:spPackage::mappings) Please add any Spark dependencies by supplying the sparkVersion and sparkComponents. Please remove: org.apache.spark:spark-streaming:1.4.0
[error] (spark-cassandra-connector-embedded/*:packageOptions) Please add any Spark dependencies by supplying the sparkVersion and sparkComponents. Please remove: org.apache.spark:spark-core:1.4.0
[error] (spark-cassandra-connector-embedded/*:spPackage::mappings) Please add any Spark dependencies by supplying the sparkVersion and sparkComponents. Please remove: org.apache.spark:spark-core:1.4.0
[error] ({.}/*:spName) Please set your Spark Package name using spName.
```

**Comment by pkolaczk** [comment]
+1 it works, I was able to release 1.4.0-M3 version to spark packages website.

**Comment by RussellSpitzer** [comment]
@pkolaczk We should merge this in :)

**Comment by RussellSpitzer** [comment]
Fixed in different PR

**Pull request closed without merging**
