### PR TITLE
SPARKC-302: Update Cassandra Driver to 3.0.0-beta1

### PR DESCRIPTION
**Pull request by jacek-lewandowski**

### CODE REVIEW

**Comment by bcantoni** [comment]
Add to changes.txt? Otherwise +1 assuming the builds finish correctly.

**Comment by jacek-lewandowski** [comment]
@bcantoni i think it would be better to add the update to the final release of Java driver, because this will override other such updates for this connector version anyway.

**Comment by jacek-lewandowski** [comment]
build this please

**Comment by jacek-lewandowski** [comment]
test this please

**Pull request merged**
