### PR TITLE
SPARKC-220: Changed default query timeout from 12 seconds to 2 minutes

### PR DESCRIPTION
**Pull request by jacek-lewandowski**

### CODE REVIEW

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by pkolaczk** [comment]
+1

**Comment by jacek-lewandowski** [comment]
test this

**Comment by jacek-lewandowski** [comment]
retest this

**Comment by jacek-lewandowski** [comment]
test this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
test this please

**Pull request merged**
