### PR TITLE
SPARKC-299 Support append data to collection column for Spark SQL

### PR DESCRIPTION
**Pull request by alexliu68**
Support appending data to collection. to set pre-append per column base, 
<column_nam>.preappred should be set to true in table options.

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
I kind of think the behavior should be slightly different. Rather than specifying column.preappend maybe we should have it were you can specify a columnname then the same word used in the scala api.

So
The equivalent of
```scala
listElements.saveToCassandra("ks", "collections_mod", SomeColumns("key", "lcol" append))
prependElements.saveToCassandra("ks", "collections_mod", SomeColumns("key", "lcol" prepend))
```

Would be something like 
```
listElements
  .write
  .format("org.apache.spark.sql.cassandra")
  .option(Map("keyspace" -> "ks", "table" -> "collections_mod", "lcol.collectionBehavior" -> "append")
  .save()

and 

prependElements
  .write
  .format("org.apache.spark.sql.cassandra")
  .option(Map("keyspace" -> "ks", "table" -> "collections_mod", "lcol.collectionBehavior" -> "prepend")
```
We could even drop collectionBehavior and just do `"lcol" -> "prepend"`

**Comment by bcantoni** [comment]
Triage: @alexliu68 will rebase this off master (for 2.0).

Alex please also add user docs if applicable.

**Comment by alexliu68** [comment]
Default is append, user only set column.preappend to true if it's not default behavior. 

It's slightly easier/simpler to use than column -> append. As user only need set it to true instead of prepend.

**Comment by alexliu68** [comment]
replace it by https://github.com/datastax/spark-cassandra-connector/pull/1043

**Pull request closed without merging**
