### PR TITLE
SPARKC-234 Added C* schema cache refresh to CassandraSQLContext

### PR DESCRIPTION
**Pull request by alexliu68**

### CODE REVIEW

**Comment by bcantoni** [comment]
Let's also add something in the docs explaining how and when to use this.

**Comment by alexliu68** [comment]
Added docs to explain when to use it

**Comment by RussellSpitzer** [comment]
I think this is a good idea and am +1 but is there a way we can make this possible from within the SQL Dialect as well?

**Comment by alexliu68** [comment]
please test it

**Pull request merged**
