### PR TITLE
SPARKC-433: Fix 'ORDER BY' and 'LIMIT' order in query

### PR DESCRIPTION
**Pull request by bryanv**
LIMIT should be after ORDER BY

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
Does this break the connector? Could you add a test?

**Comment by bcantoni** [comment]
Triage: We need to add a test to this PR and create a corresponding JIRA.

**Comment by RussellSpitzer** [comment]
Made Jira SPARKC-433 and I'm gonna make a new branch targeting 1.2 -> present

**Comment by RussellSpitzer** [comment]
Closing this for https://github.com/datastax/spark-cassandra-connector/pull/1042

**Pull request closed without merging**
