### PR TITLE
SPARKC-171: Upgrade to Spark 1.1.1

### PR DESCRIPTION
**Pull request by jacek-lewandowski**

### CODE REVIEW

**Comment by pkolaczk** [comment]
+1, please squash

**Comment by jacek-lewandowski** [comment]
@pkolaczk well.. actually i had another idea - i want to leave these two commits so that I can skip Upgrade to Spark 1.1.1 during merge to b1.2 and master, wdyt?

**Comment by pkolaczk** [comment]
Fair enough. You'll need to do some magic to achieve this:
http://stackoverflow.com/questions/727994/git-skipping-specific-commits-when-merging

**Comment by jacek-lewandowski** [comment]
yup, i've found exactly the same post ;)

**Pull request merged**
