### PR TITLE
SPARKC-429: Test Reused Exchange SPARK-17673

### PR DESCRIPTION
**Pull request by RussellSpitzer**
This tests an error in Spark which was present in 2.0.0 but should be
fixed in 2.0.1

https://issues.apache.org/jira/browse/SPARK-17673

### CODE REVIEW

**Comment by jtgrabowski** [comment]
+1

**Comment by RussellSpitzer** [comment]
test this please

**Comment by RussellSpitzer** [comment]
test this please

**Comment by RussellSpitzer** [comment]
test this please

**Pull request merged**
