### PR TITLE
SPARKC-269 Support smallint

### PR DESCRIPTION
**Pull request by dalaro**
Add SmallIntType case class mapped to java.lang.Short and CQL's "smallint" type

Does this need test coverage?  If there's a basic datatype spec/test somewhere that I should extend, let me know.

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
@pkolaczk Could you please take a look at this :)

**Comment by bcantoni** [comment]
@RussellSpitzer should these new types be mentioned in the docs (2_loading.md and 6_advanced_mapper.md)?

**Comment by RussellSpitzer** [comment]
Good call @bcantoni I'll add that

**Comment by pkolaczk** [comment]
+1, great job! :)

**Pull request merged**
