### PR TITLE
Compatibility with Spark 3.2

### PR DESCRIPTION
**Pull request by bbenshalom**
Continuing @alexott 's work from [1333](https://github.com/datastax/spark-cassandra-connector/pull/1333). There were tests failing and I believe the reason was the new adaptive query execution, which was [enabled by default](https://issues.apache.org/jira/browse/SPARK-33679) in 3.2.

I resolved a few tests by simply handling the case of `AdaptiveSparkPlanExec` (the `BatchScanExec` object was nested within it), and another test by including `spark_catalog` as a valid cassandra catalog name (not 100% sure this is the desired handling of this test, let me know what you think).

# Checklist:

- [x] I have a ticket in the [OSS JIRA](https://datastax-oss.atlassian.net/projects/SPARKC)
- [x] I have performed a self-review of my own code
- [x] Locally all tests pass (make sure tests fail without your patch)

### CODE REVIEW

**Comment by jtgrabowski** [comment]
Hi @bbenshalom there is a compilation error in the CI:
```
 [error] /home/runner/work/spark-cassandra-connector/spark-cassandra-connector/connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataSourceSpec.scala:289:29: wrong number of arguments for pattern org.apache.spark.sql.execution.datasources.v2.BatchScanExec(output: Seq[org.apache.spark.sql.catalyst.expressions.AttributeReference],scan: org.apache.spark.sql.connector.read.Scan,runtimeFilters: Seq[org.apache.spark.sql.catalyst.expressions.Expression])
[error]         case a@BatchScanExec(_, _: CassandraInJoin) => a
[error]                             ^
[error] one error found
[error] (connector / IntegrationTest / compileIncremental) Compilation failed
[error] Total time: 23 s, completed Apr 11, 2022 6:49:06 AM
```

**Comment by bbenshalom** [comment]
Hi @jtgrabowski , fixed. Any way for me to re-run the tests workflow myself?

**Comment by jtgrabowski** [comment]
You can run the integration tests locally with `sbt/sbt it:test`, see [this page](https://github.com/datastax/spark-cassandra-connector/blob/master/doc/developers.md#getting-started) for details. Once this PR is merged, you'll be free to run the CI tests on your own. Btw. could you please sign the DataStax Contribution License Agreement https://cla.datastax.com/ ?

**Comment by bbenshalom** [comment]
I signed the license agreement

**Comment by bbenshalom** [comment]
@jtgrabowski The test that's failing in the CI is skipped for me locally ("skipped because not DSE"), I couldn't find in the contribution tips how to define a "DSE mode"... Can you please advise or point me to the right documentation?

**Comment by jtgrabowski** [comment]
Try 
```
export CCM_CASSANDRA_VERSION=5.1.24
sbt/sbt 'it:testOnly com.datastax.bdp.spark.search.SearchAnalyticsIntegrationSpec'
```

**Comment by jtgrabowski** [comment]
It may seam to hang for a couple of minutes. The test needs to download DSE zip. The zip is downloaded to /tmp/ccm-xyz.

**Comment by bbenshalom** [comment]
@jtgrabowski it seems that the current failing test has to do with a [change](https://spark.apache.org/docs/latest/sql-migration-guide.html) in spark 3.2:

> In Spark 3.2, DataFrameNaFunctions.replace() no longer uses exact string match for the input column names, to match the SQL syntax and support qualified column names. Input column name having a dot in the name (not nested) needs to be escaped with backtick `. Now, it throws AnalysisException if the column is not found in the data frame schema. It also throws IllegalArgumentException if the input column name is a nested column. In Spark 3.1 and earlier, it used to ignore invalid input column name and nested column name.

In other words, for the column name `~~funcolumn`, the dataframe filter generated is ``~~funcolumn``. I could just remove backticks from the column names in the code, but it doesn't seem right, since the intention of the Spark change seems to be to avoid "weird" column names. Do you think it would be better to simply remove the test and not support this functionality?

**Comment by jtgrabowski** [comment]
I'm hesitant on just dropping the support for this. Could we match the column name with the backticks instead?

**Comment by bbenshalom** [comment]
@jtgrabowski I tried to match the column names with the backticks while building the cassandra filters, and indeed the execution plan was displayed correctly. However, the test then failed on the collect() method of the DataFrame, again because of the same mismatch. The filter already has the backticks in it when it is passed to `CassandraScanBuilder` (called by spark code)...

Spent quite a bit of time on this and couldn't find a way around it. Open to suggestions...

**Comment by jtgrabowski** [comment]
I didn't have time to look into it yesterday. I'll try to help next week.

**Comment by jtgrabowski** [comment]
@bbenshalom here is a PR that should fix the offending test: https://github.com/bbenshalom/spark-cassandra-connector/pull/1. Please take a look when you get a chance.
I also created this: https://datastax-oss.atlassian.net/browse/SPARKC-677 as the "weird column names" are not fully supported. The problems appear with the older Spark versions too, so I don't think it should block us from moving forward with this PR.

**Comment by bbenshalom** [comment]
@jtgrabowski thanks for the PR. Do you have any plan as to when we can merge & release a new version (even a release candidate)?

**Review by jtgrabowski — APPROVED** [review]

**Comment by jtgrabowski** [comment]
We need to do some behind-the-scenes testing before we can release. I'll kick off the performance tests and let you know.

**Comment by jtgrabowski** [comment]
@bbenshalom @alexott thank you for your contribution! This is now merged!

**Comment by bbenshalom** [comment]
@jtgrabowski thank you for your patience and great support! Was a pleasure!

**Comment by jtgrabowski** [comment]
perf results are ok, the release is scheduled for next week :+1:

**Pull request merged**
