### PR TITLE
Upgrade to spark2.3.0 and cassandra driver 3.4

### PR DESCRIPTION
**Pull request by schernolyas**
Hi

### CODE REVIEW

**Comment by bepcyc** [comment]
Hi. 

Are there any plans on when this PR is gonna be merged? Apache Spark 2.3.0 has been released 2 months ago already.

**Comment by Fatmali** [comment]
+1 we really need this

**Comment by ManuelWeiss** [comment]
@bcantoni any chance you can merge this?

**Comment by Saarus** [comment]
+1. Please get this merged ASAP.

**Comment by jfgosselin** [comment]
+1 we need this

**Comment by RussellSpitzer** [comment]
Please post PR's on the corresponding Jira Ticket as we do not check Github Pull requests without corresponding Jiras. 

This PR has a few problems. There are several unrelated version changes that are not explained and don't seem to be critical to the PR. In addition there is a typo(?) in the comment section where spark is renamed to sparkexit. If we want to change versions of other components that's fine but should be done separately.

 The main issue though is that the fix is a workaround for the missing class. This will break compatibility with Spark 2.0-2.2. I think the correct thing to do here is to completely remove the SparkReflectionLock from the Spark Cassandra Connector as well as the Scala 2.10 compatibility code. This would bring our testing back up to green and we wouldn't have to worry about this issue in the future. 

So in my eyes a Spark 2.3.0 branching event requires
* Removal of SparkReflectionLock
* Removal of Scala 2.10 support
* All supported integration tests run green (Hopefully this is just free after removing Scala 2.10)

**Comment by schernolyas** [comment]
Hi @RussellSpitzer !

Thanks for comment!  The PR working in my customer environment. And I think we don't need change something.  
About Jira ... Okey. Please put link to your jira.

**Comment by RussellSpitzer** [comment]
Closing this Pull request, since we merged the other SPARKC-530 ticket. Please open a new Jira for any other modifications you may want or need.

**Pull request closed without merging**
