### PR TITLE
SPARKC-501: added a histogram which records the distribution of the rows in batches

### PR DESCRIPTION
**Pull request by cip123**
I added a histogram only for row count. If needed I can easily add similar histograms for bytes written, duration, even wait times.

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
Looking good, let me see if the tests can get kicked off

**Comment by RussellSpitzer** [comment]
this test please

**Comment by cip123** [comment]
Minor re-factorization of the tests. Please let me know if I missed something. I also sent you an email, not sure if you received it or entered spam cause it was from a new email address

**Comment by RussellSpitzer** [comment]
Yep got your message, you can always ping me on the Jira to make sure I get the update :)

**Comment by RussellSpitzer** [comment]
Tested manually on my box, all green!

**Comment by RussellSpitzer** [comment]
Merged and will be backporting to b2.0

**Pull request merged**
