### PR TITLE
SPARKC-307: Upgrade Cassandra in integration tests to 3.0.2

### PR DESCRIPTION
**Pull request by jacek-lewandowski**

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
+1, If we can understand why Travis hates starting c* now (i've noticed this before ....)

**Comment by RussellSpitzer** [comment]
Nvm it's a bad java version ..  Unsupported major.minor version 52.0

**Comment by RussellSpitzer** [comment]
@jacek-lewandowski We need to target this at 1.5 as well since we are missing some bugs See SPARKC-303

**Comment by jacek-lewandowski** [comment]
Closing this PR in favour of https://github.com/datastax/spark-cassandra-connector/pull/924

**Pull request closed without merging**
