### PR TITLE
SPARKC-123: Synchronized Reflection Util Access

### PR DESCRIPTION
**Pull request by RussellSpitzer**

### CODE REVIEW

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please please please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by RussellSpitzer** [comment]
retest this please

**Comment by RussellSpitzer** [comment]
please please please pretty please

**Comment by jacek-lewandowski** [comment]
@RussellSpitzer find more invocations of `.tpe` in the project and synchronise them on just in case

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
+1

**Comment by pkolaczk** [comment]
+1

**Pull request merged**
