### PR TITLE
Wip upgrade spark 1.2.0

### PR DESCRIPTION
**Pull request by jacek-lewandowski**

### CODE REVIEW

**Comment by pkolaczk** [comment]
+1, needs rebasing and squashing into a single commit though.

**Comment by helena** [comment]
ok

**Comment by omriiluz** [comment]
Not sure this is the right place to post this, let me know if there's another place more suitable.
I've been using this branch for the last few days in our testing environment with spark 1.2, and it's working fine. I've used two main workloads - a feeder from Kafka to Cassandra using spark-streaming and a query engine using spark-sql to query data on Cassandra - both are not showing any issues after upgrading to 1.2 with this branch.

**Comment by helena** [comment]
Hi @omriiluz this being a `WIP` branch it's still work in progress,  i.e. not in the releasable state. That said, we really just have one or two more features to merge in which relate to our PRs against spark, and that is the holdup for cutting the release - but note: this is going first to alpha!! We will announce the alpha release on the user mailing list.

**Comment by jacek-lewandowski** [comment]
ok this branch seems to be obsolete now

**Pull request closed without merging**
