### PR TITLE
Added support for SSL connections

### PR DESCRIPTION
**Pull request by rstrickland**

### CODE REVIEW

**Comment by pkolaczk** [comment]
@jacek-lewandowski  can you take a look at this?

**Comment by jacek-lewandowski** [comment]
please rebase it

**Comment by rstrickland** [comment]
All the relevant properties are exposed by default: http://docs.oracle.com/cd/B19306_01/java.102/b14355/sslthin.htm#BABJIHFJ.  The driver uses the default options when you call the default SSLOptions constructor, which results in the JVM respecting these system JSSE properties.

**Comment by rstrickland** [comment]
Also, do you mean for me to rebase against master?

**Comment by jacek-lewandowski** [comment]
@rstrickland yes - rebase against the master

For the SSL settings - so if you set them on the client host you will have to pass them also as `spark.executor.extraJavaOptions`. Don't you think that adding them to Spark configuration and distributing them this way is better?

Also - what about Thrift based connections?

**Comment by rstrickland** [comment]
I went down this road initially, but then it seemed like wheel reinvention.  But I can see it both ways.  I'm happy to add spark options if you'd like to go that route.

**Comment by jacek-lewandowski** [comment]
@rstrickland IMHO that would be better. Especially because we've recently moved all the connection parameters into Spark configuration. This has also one more benefit - it allows us to introduce namespace in Spark configuration to setup connections to different clusters.

**Comment by jacek-lewandowski** [comment]
@rstrickland are you going to work on this?

**Comment by rstrickland** [comment]
@jacek-lewandowski it's on my radar, but I've been distracted by other stuff lately.

**Comment by jacek-lewandowski** [comment]
@rstrickland could you create a ticket in Jira for this ticket and add a link to this branch?

**Comment by RussellSpitzer** [comment]
I'm pretty sure this is done (since we have a lot of ssl options :P) but just incase i'm missing something to we still need this?

**Comment by jacek-lewandowski** [comment]
Closing this - we already have SSL support and client auth is covered by SPARKC-359

**Pull request closed without merging**
