### PR TITLE
updated documentation to save others time doing what might be a common task

### PR DESCRIPTION
**Pull request by sheldonkhall**
I had to create a cassandra table with a more complicated primary key structure than shown in the documentation examples. I finally figured out how to do this from the source code and thought I could save some others time by sharing what I have done.

### CODE REVIEW

**Comment by jacek-lewandowski** [comment]
Thanks for the patch.

Could you create a ticket in Jira, squash your commits, and prepend the result commit title with "SPARKC-xxx: "

**Comment by sheldonkhall** [comment]
OK I think I have done this now. I am new to the system so let me know if I need to make any further changes.

https://datastax-oss.atlassian.net/projects/SPARKC/issues/SPARKC-232?filter=allopenissues

**Comment by RussellSpitzer** [comment]
I think Jacek was asking if you could present a single commit rather than 5, you should be able to do this using the get rebase command. I prefer using git rebase -i target_branch 
Then you'll see you can change the commit labels from keep to squash

See 
http://jaimeiniesta.github.io/learn.github.com/p/rebasing.html
For more info

When you have done this correctly you'll have to force push back up to your branch and this PR will end up only having a single commit in it 

Thanks so much for helping out!

**Comment by sheldonkhall** [comment]
I think that I have done this correctly now, thanks for the help!

**Comment by RussellSpitzer** [comment]
Yep that's it! Thanks for the update!

**Pull request merged**
