### PR TITLE
SPARKC-241: Spark 1.5 integration

### PR DESCRIPTION
**Pull request by jacek-lewandowski**

### CODE REVIEW

**Comment by jacek-lewandowski** [comment]
rebuild this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by pkolaczk** [comment]
+1

**Pull request merged**
