### PR TITLE
SPARKC-201 Support upper case charactors in UDT

### PR DESCRIPTION
**Pull request by alexliu68**
Quoted column name so that UDT type can find
the column

### CODE REVIEW

**Comment by pkolaczk** [comment]
+1

**Comment by pkolaczk** [comment]
retest this please

**Comment by alexliu68** [comment]
retest it please

**Comment by alexliu68** [comment]
retest it please

**Comment by alexliu68** [comment]
retest it please

**Comment by alexliu68** [comment]
The failing test is not related to this ticket. Tests pass at my local

**Pull request merged**
