### PR TITLE
SPARKC-119: Fix ScalaDoc warnings. Fix broken internal ScalaDoc links. R...

### PR DESCRIPTION
**Pull request by pkolaczk**
...emove invalid external ScalaDoc links.

### CODE REVIEW

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
retest this please

**Comment by sdelmas** [comment]
retest this please

**Comment by sdelmas** [comment]
retest this please

**Comment by sdelmas** [comment]
retest this please

**Comment by jacek-lewandowski** [comment]
let me try to add mapping to external libraries - at least to Spark and Akka

**Comment by jacek-lewandowski** [comment]
@pkolaczk take a look at my PR and merge it eventually if you like: https://github.com/datastax/spark-cassandra-connector/pull/627

**Comment by jacek-lewandowski** [comment]
+1

**Pull request merged**
